image: openjdk:21
packages:
  - maven
sources:
  - https://git.sr.ht/~paxel/dedup
tasks:
  - dependencies: |
      cd dedup
      mvn -B de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies
  - build_and_test: |
      cd dedup
      mvn package -B